version: '3.7'

services:
  mysql-container:
    image: mysql:8.0.18
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: "cs_dough_db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "cs_dough_pass"
      MYSQL_USER: "cs_dough"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  tomcat:
    image: tomcat:9.0.30-jdk8
    restart: always
    container_name: tomcat
    depends_on:
      - mysql-container
    ports:
      - "8080:8080"
    volumes:
      - ./target/cs-dough-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war