package by.training.constant;


public enum AttributesContainer {

    /**
     * Keep alphabetically
     */

    CLOSE,
    COMMAND,
    COUNTRY,
    DRIVER,
    EMAIL,
    ERROR,
    EMAIL_CORRECTNESS_ERROR,
    EMAIL_ERROR,
    EMAIL_UNIQUENESS_ERROR,
    EN,
    END_DATE,
    FINAL_GAME,
    GAME,
    GAMES,
    GAME_TYPE,
    ID,
    LANGUAGE,
    LATEST_GAMES,
    LOCALE,
    LOGO,
    LOGIN,
    MESSAGE,
    NAME,
    NAME_ERROR,
    NAME_UNIQUENESS_ERROR,
    NICKNAME,
    NICKNAME_ERROR,
    NICKNAME_UNIQUENESS_ERROR,
    ORGANIZER,
    PASSWORD,
    PASSWORD_CONFIRMATION,
    PASSWORD_CONFIRMATION_ERROR,
    PASSWORD_CORRECTNESS_ERROR,
    PASSWORD_ERROR,
    PRIZE_POOL,
    PLAYER,
    PLAYERS,
    PLAYER_ID,
    PLAYERS_NUMBER,
    REFERER,
    RU,
    SETTINGS,
    SIGN_IN,
    SIGN_IN_ERROR,
    START_DATE,
    STRING_LOCALE,
    SURNAME,
    TOURNAMENT,
    TOURNAMENT_ID,
    TOURNAMENTS,
    UNAVAILABLE_ERROR,
    URL,
    USER,
    USER_ROLE,
    USER_TO_PROCESS,
    USERNAME,
    USERNAME_CORRECTNESS_ERROR,
    USERNAME_ERROR,
    USERNAME_OR_PASSWORD_ERROR,
    USERNAME_UNIQUENESS_ERROR;

    @Override
    public String toString() {
        return this.name().toLowerCase();
    }

}
